### ISSUE TITLE
Suggestion list

### ISSUE THREAD

**Issue by FurnyGo** [Zailer43/FZMM-Mod#10]
- [x] Add format variations in the gradient generator for chat and plugins (as in https://rgb.birdflop.com)
---
- [x] Add the history of the entered values to the lines of the "Book Title" type and the history of the generated items
---
- [x] Replace the vanilla error messages with guides on how to use the command
![image](https://user-images.githubusercontent.com/68079109/188450532-82607be2-3642-45e2-9742-47f549434c02.png)
---
- [x] Add the addition of accessories to the skin like a Head Generator, but in the form of a skin to install it in the game

**Comment by Zailer43** [comment]
ok it makes sense if you want to do things like gradients similar

**Comment by FurnyGo** [comment]
5. The ability to translate this text
![image](https://user-images.githubusercontent.com/68079109/188630335-c99b8072-7747-4ccb-b226-f24a1ad5e583.png)

**Comment by FurnyGo** [comment]
- [ ] "Replace "block" with "%s" in ``"itemGroup.fzmm.useful_block_states.item.waterloggedBlock": "Waterlogged block"``

**Comment by Zailer43** [comment]
> * [ ]  "Replace "block" with "%s" in `"itemGroup.fzmm.useful_block_states.item.waterloggedBlock": "Waterlogged block"`

I should put:
- `Waterlogged %s` = Waterlogged stone slab
- `Waterlogged double %s` = Waterlogged double stone slab
- `Waterloogged block (%s)` = Waterlogged block (stone slab)
?
I did not do it since the "slab" does not convince me since when placing it it is a block

**Comment by FurnyGo** [comment]
Waterlogged block of/from %s

**Comment by FurnyGo** [comment]
And you can also add such variations as type "top" and waterlogged "true"; type "top"; waterlogged "true"; type "double"

**Comment by Zailer43** [comment]
yes but I find this one more curious since it looks like a normal block and when you break it it changes to water, in the variations with the slab up or down you see the water and it has physics

**Comment by FurnyGo** [comment]
- [ ] Add ``{Count:1b,id:"minecraft:mangrove_roots",tag:{BlockStateTag:{waterlogged:"true"}}}``

**Comment by FurnyGo** [comment]
Add an head image generator (every 16x16 pixels per photo = 1 head)

**Comment by Zailer43** [comment]
> Add an head image generator (every 16x16 pixels per photo = 1 head)

yes, actually some time ago I had in mind a "HeadWall" where each 8x8 of an image is a head and a wall of heads placed next to each other and on top of it extends to form the image you passed to it

**Comment by White-145** [comment]
Add 1.19 version pls

**Comment by Zailer43** [comment]
> Add 1.19 version pls

I'm sorry, but I prefer to only support the latest version

**Comment by Zailer43** [comment]
> Add the addition of accessories to the skin like a Head Generator, but in the form of a skin to install it in the game

do you consider this done in https://github.com/Zailer43/FZMM-Mod/commit/72838ca981401a0f4d2fec1e6c32d9ca1c22a28d?
as currently you can save the skin and you can overlay a texture on any part of the skin if you add the texture by resource pack and then use it as a layer, and I don't intend to do something to be able to update your skin in-game as I think it would not be related to the mod.
