### ISSUE TITLE
Incompatible with Tweaker More 

### ISSUE THREAD

**Issue by theendercore** [Zailer43/FZMM-Mod#16]
There seams to be some mixin conflict with the Tweaker More mod.
Specifically with the malilib fi.dy.masa.malilib.gui.widgets.WidgetConfigOption class. 
I think at least here is the log :
https://mclo.gs/9DZAcuS

**Comment by Zailer43** [comment]
when i switch from malilib to owo lib this should be fixed

Mental note: do not use overwrite in the future

**Comment by Zailer43** [comment]
fixed in 0.1.0-BETA-3
