### ISSUE TITLE
How does the encryption book seeds work exactly ?

### ISSUE THREAD

**Issue by Cec-Krem** [Zailer43/FZMM-Mod#36]
Hello, I just wanted to know, how is it possible to create, in a resource pack, a correct encrypt key according to a certain seed ? I don't see any logic connection between the 2 keys in the example resource pack, so I don't have a clue on how to do something for any other seed than 0 or 1, which I'd like to do.

### Thanks for reading

**Comment by Zailer43** [comment]
To create the decryptor for a specific seed you must go to the book encrypt gui, select the configuration you want to use (seed, translation key, etc), click on the bottom left corner button "get decrypt", go to the chat, click on the message to copy it, then go to the translation file, add a comma at the end of the last line before the bracket, in the next line paste what you copied and that's it, then you can save the file and you can decrypt that configuration (seed, translation key, etc).

This solves your doubts? sorry if I explained badly or little in the wiki.

**Comment by Cec-Krem** [comment]
Oh, thank you so much ! I never really paid attention at this button, since I wasn't using it... thanks for the reply :)
