### ISSUE TITLE
[Suggestion] Skin generator/editor

### ISSUE THREAD

**Issue by mrilgiz** [Zailer43/FZMM-Mod#39]
Translation:
> I would like to see a similar head generator, but with an editor not only for heads but also for other body parts. It would be great if you could save the skin quickly, then share it in the Discord chat and from there use the command /skin [skin link] to apply it.

Original message:
> Хотелось бы видеть такой же генератор голов но уже с редактором не только голов но и других частей тела тип
сохраняешь скин быстро перекидываешь в  чат дискорд скин и оттуда уже через /skin [ссылка на скин]
устанавливаешь скин

**Comment by Zailer43** [comment]
Hello, I appreciate if we speak in English so we can understand each other better

Currently, the mod can edit the body of the skin, both by overlaying a texture and editing with models. However, there is currently no preview of the body shown, and none is included by default. But you can refer to the wiki [here](https://github.com/Zailer43/FZMM-Mod/blob/1.19.4/dev/docs/en/wiki/head_generator/0.2.0_head_generator.md) to see how to add it with a resource pack

I will take into account improving the preview when modifying the rest of the body and also adding some examples to the default resource pack

**Comment by Zailer43** [comment]
this was added in https://github.com/Zailer43/FZMM-Mod/releases/tag/0.2.3
