### ISSUE TITLE
Crashes when used with sodium extra 4.27

### ISSUE THREAD

**Issue by omakthe1st** [Zailer43/FZMM-Mod#44]
The game crashes when opening the GUI or doing anything related to this mod if Sodium Extra is installed, it works fine with sodium just crashes with extra installed

**Comment by Zailer43** [comment]
Sorry for taking so long to respond; it seems to be a compatibility issue with sodium extra 4.27 and owo-lib. However, in the latest versions, this has been resolved. It doesn't seem to be directly related to the fzmm mod
