### ISSUE TITLE
Cannot search with symbol chat widget

### ISSUE THREAD

**Issue by CkreaM** [Zailer43/FZMM-Mod#45]
Unable to search when writing formatted text in the text generator, not sure why but it just won't let me search for stuff.

**Comment by CkreaM** [comment]
Same with the image text generator

**Comment by Zailer43** [comment]
Fixed in https://github.com/Zailer43/FZMM-Mod/commit/61df86bd3507c16e4d39ec2c6ba3e781a003ceb5
