### ISSUE TITLE
1.20.2 Support

### ISSUE THREAD

**Issue by CkreaM** [Zailer43/FZMM-Mod#48]
PLEASE, it would be incredible, so many servers are moving to villager nerf version

**Comment by CkreaM** [comment]
this is the only mod I need to update

**Comment by JayRPlayz** [comment]
PLEASE, we NEEED this update! especially, because 1.20/.1 isnt compatible with 1.20.2

**Comment by Zailer43** [comment]
fixed in https://github.com/Zailer43/FZMM-Mod/commit/fddc552fcd67fcdfda06f0158ab6e25b4b7c6113
duplicate of #46
