### ISSUE TITLE
[SUGGESTION] Rename execute to done for clarity

### ISSUE THREAD

**Issue by Daniel99j2** [Zailer43/FZMM-Mod#52]
When selecting options in the editors, there is an execute button. This button is basically a done button, however it seems more like a give button currently.
I suggest what you rename
 "fzmm.gui.button.execute": "Execute",
to
 "fzmm.gui.button.execute": "Done",

**Comment by Zailer43** [comment]
Ah, okay, sorry if the English translation is incorrect, I'm not fluent in English (I speak Spanish), so should I change the "Execute" in that translation to "Done" in imagetext, select item screen, and player statue? (although player statue usually takes 1-2 minutes to generate the item?)

**Comment by Daniel99j2** [comment]
Yeah
