### ISSUE TITLE
Get an invisible item frame in operator utilities causes kick

### ISSUE THREAD

**Issue by MadVanz** [Zailer43/FZMM-Mod#54]
Whenever I try to take the Invisible Item Frame or Invisible Glow Item Frame from the Operator Utilities Tab, it gives me an error.

![javaw_6xhMTSohnE](https://github.com/Zailer43/FZMM-Mod/assets/131803935/b72945f5-6996-4c43-8bad-d78b9891836a)

**Comment by Zailer43** [comment]
Thanks for reporting this, apparently I missed it when I upgraded to 1.20.5, it was fixed in 
 https://modrinth.com/mod/fzmm/version/0.2.12
