### ISSUE TITLE
Some functions have no description

### ISSUE THREAD

**Issue by FurnyGo** [Zailer43/FZMM-Mod#6]
![image](https://user-images.githubusercontent.com/68079109/188316720-210a3d24-10f3-4f39-a2cf-7e7597f7dbab.png)
![image](https://user-images.githubusercontent.com/68079109/188316735-aace5ea2-9703-47b3-b010-b7dd82ca38b6.png)

**Comment by Zailer43** [comment]
the parse in slot is bug, the encryptbook what happens is that I haven't documented it since I have to explain how to use it well, now when I try to document it and I add a page on the wiki about how to use it

**Comment by FurnyGo** [comment]
![image](https://user-images.githubusercontent.com/68079109/188317881-2467ff19-4d29-4cf2-b4f5-679cd0334c35.png)
![image](https://user-images.githubusercontent.com/68079109/188317890-0ac8f0bf-fa6c-4a28-ade7-de2cefbbee8e.png)
I think copyItemName doesn't have a personal description

**Comment by Zailer43** [comment]
do you think i should put:

copyItemNameJson:
Copy the **JSON** of the name of the item that you have the cursor over in an inventory

Example: {"text":"Hello World","color":"red"}

---
copyItemName:
Copy the **text** of the name of the item that you have the cursor over in an inventory

Example: Hello world

**Comment by FurnyGo** [comment]
![image](https://user-images.githubusercontent.com/68079109/188932766-2219f38e-f604-4433-b2d1-28a1fb134052.png)
