### ISSUE TITLE
Bug list 2

### ISSUE THREAD

**Issue by FurnyGo** [Zailer43/FZMM-Mod#9]
- [x] The buttons are shifted to the left, not aligned in the middle when translating
![image](https://user-images.githubusercontent.com/68079109/188434386-828ba21c-fa55-488f-8f74-30cde012b0de.png)
---
- [x] The translated text in the head generator goes beyond the button
![image](https://user-images.githubusercontent.com/68079109/188443584-0879380b-dbb6-4e38-924d-a5f8a130b266.png)
---
- [x] The /fzmm skull nickname command issues a head with a skin that can be installed via the SkinsRestorer plugin, but you can't do that in Head Generator

**Comment by Zailer43** [comment]
> 3. The /fzmm skull nickname command issues a head with a skin that can be installed via the SkinsRestorer plugin, but you can't do that in Head Generator

The truth is that I originally wanted to do that but I couldn't find a way and I ended up getting the skin from the cache and it seems that the cache only has the skin loaded if you have the player entity loaded

**Comment by FurnyGo** [comment]
- [ ] 4. Head Generator does not have a "Back" button

**Comment by FurnyGo** [comment]
- [ ] 5. ![image](https://user-images.githubusercontent.com/68079109/188932766-2219f38e-f604-4433-b2d1-28a1fb134052.png)

---

- [ ] 6. 1.19 paintings have no translation

![image](https://user-images.githubusercontent.com/68079109/188932981-07d7933b-a084-4cd7-a8ea-01bb22570ee1.png)

**Comment by Zailer43** [comment]
> 6. paintings have no translation

the issue is that there is no minecraft translation of the paintings and they are added when they are not in the placeable paintings tag, so I would have to add translation to all the paintings

**Comment by FurnyGo** [comment]
![image](https://user-images.githubusercontent.com/68079109/189201206-9d9255b2-e267-4c8d-adbb-70599b47004d.png)
Missing a space in the asymmetricEncryptKey description
